### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by wyzjack** [bcmi/TopNet-Object-Placement#3]
Thanks for the implementation! I am wondering is there code in the repo that can generate the bbox predicted? It seems that in the test.py, the model output is a binary classification prediction.

I would appreciate it very much if you could reply.

**Comment by ustcnewly** [comment]
You can refer to the code in FOPA https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment,  "python test.py --mode composite"

**Comment by wyzjack** [comment]
Great, thanks!
